### ISSUE TITLE
DockerFile is not complete

### ISSUE THREAD

**Issue by clescot** [nickbreen/docker-mysql-backup-cron#1]
Hi,
it seems backup.sh and restore.sh are not part of the DockerFile, nor the crontab is in place.

can you update your project?

best regards,

Charles.

**Comment by nickbreen** [comment]
Oops! Sure thing.

**Comment by nickbreen** [comment]
Updated. Though, please be warned, this is actually an untested image. I.e. right now, the `s3cmd` doesn't actually work.
