### ISSUE TITLE
set a version when release is pushed on the docker registry

### ISSUE THREAD

**Issue by clescot** [nickbreen/docker-mysql-backup-cron#4]
Hi,
thanks for your work.
Can you set a version when you publish your image to the docker registry?
all versions are actually bound to the 'latest' release, which prevent to select a specific one.

best regards,

Charles.

**Comment by nickbreen** [comment]
Sure thing.

**Comment by nickbreen** [comment]
Updated with `v1.0.1`, there _should_ have been a v1.0.0 but I'd mis-configured the build settings.
