### ISSUE TITLE
backup.sh and restore.sh are not consistent about S3 bucket name 

### ISSUE THREAD

**Issue by clescot** [nickbreen/docker-mysql-backup-cron#5]
Hi,
/backup.sh works like a charm.
but when i want to list available backups via the /restore.sh command,
an error occurs : 

```
ERROR: Bucket 's3:' does not exist
ERROR: S3 error: 404 (NoSuchBucket): The specified bucket does not exist
```

according to this line https://github.com/nickbreen/docker-mysql-backup-cron/blob/master/restore.sh#L14 , BUCKET should not start with 's3://' prefix, but this is required by the backup.sh command.
When i remove from the BUCKET variable the s3:// prefix, it lists available backups successfully, but further backups fail.
best regards,
Charles.

**Comment by nickbreen** [comment]
Ah yes. I switched between the prefix and without. I'll update the restore
script, feel free to fork and send a PR if you urgently need it.
