### ISSUE TITLE
cron expression does not seems to work 

### ISSUE THREAD

**Issue by clescot** [nickbreen/docker-mysql-backup-cron#7]
Hi,
i've tried to override the cron expression CRON_D_BACKUP with this expression : 
`CRON_D_BACKUP: "* * * * * root   /backup.sh | logger"`, 
but it does not seems to work....
I don't see any reference of CRON_D_BACKUP on the project, except in the Dockerfile.
How does the cron expression is set to the system?

best regards,

Charles.

**Comment by nickbreen** [comment]
The cron features are part of the upstream image (nickbreen/cron). 

There should be a symlink:
    /etc/cron.d/BACKUP -> /etc/container_environment/CRON_D_BACKUP 

The default value set in `Dockerfile` is missing a newline. The `docker-compose.yml` file is also using `|-` rather than `|` which I'll also fix.

E.g.

```
    CRON_D_BACKUP: |
      # Run at strange (UTC) hours, (14,22,06 NZDT, 13,21,05 NZST)
      0 1,9,17    * * *   root /backup.sh | logger
```

**Comment by nickbreen** [comment]
There should be log lines in the docker logs like this:

```
backup_1 | Feb 19 21:51:01 5df6e54bf8ee /USR/SBIN/CRON[55]: (root) CMD (/backup.sh | logger)
backup_1 | Feb 19 21:51:02 5df6e54bf8ee /USR/SBIN/CRON[54]: (CRON) info (No MTA installed, discarding output)
```

**Comment by clescot** [comment]
Hi,
i confirm the fix, cron expression works!
thanks a lot!
The only remaining bug is towards database restoration....(#6)
Charles.
